"""empty message

Revision ID: 187a882ec49f
Revises: 
Create Date: 2021-02-14 12:02:09.617405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187a882ec49f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('place', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('image_logo', sa.String(length=200), nullable=True),
    sa.Column('image_menu', sa.String(length=200), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    # ### end Alembic commands ###
